pipeline {
    agent any
    
    tools {nodejs "nodejs"}
    
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
         stage('Test case Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
       
    }
}
