pipeline {
    agent any
    
    tools {nodejs "nodejs"}
    stages{
stage('SCM CHECKOUT'){
steps{

git 'https://github.com/arko489/simple-node-js-react-npm-app.git'
}
}
    
   
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
       
    }
}
